version: '3.8'

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_DEVICE=<NETWORK_INTERFACE> # e.g., eth0
      - LANG=en
      - WG_HOST=<PUBLIC_ID>
      - PASSWORD_HASH=<HASHED_PASSWORD>
      - PORT=51822
      - WG_PORT=51821
    volumes:
      - /etc/wireguard:/etc/wireguard
    ports:
      #- "51821:51820/udp"
      - "51822:51822/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    restart: unless-stopped


